export type RevelationType = 'Mekki' | 'Medeni';

export interface SurahMeta {
  number: number;
  nameTr: string;
  revelation: RevelationType;
}

// Widely accepted Medenî (Medinan) surahs.
const MEDENI_NUMBERS = new Set<number>([
  2, 3, 4, 5, 8, 9, 13, 22, 24, 33, 47, 48, 49, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76, 98, 99, 110,
]);

// Turkish surah names (1-114)
const NAMES: Array<{ number: number; nameTr: string }> = [
  { number: 1, nameTr: 'Fâtiha' },
  { number: 2, nameTr: 'Bakara' },
  { number: 3, nameTr: 'Âl-i İmrân' },
  { number: 4, nameTr: 'Nisâ' },
  { number: 5, nameTr: 'Mâide' },
  { number: 6, nameTr: 'En’âm' },
  { number: 7, nameTr: 'A’râf' },
  { number: 8, nameTr: 'Enfâl' },
  { number: 9, nameTr: 'Tevbe' },
  { number: 10, nameTr: 'Yûnus' },
  { number: 11, nameTr: 'Hûd' },
  { number: 12, nameTr: 'Yûsuf' },
  { number: 13, nameTr: 'Ra’d' },
  { number: 14, nameTr: 'İbrâhîm' },
  { number: 15, nameTr: 'Hicr' },
  { number: 16, nameTr: 'Nahl' },
  { number: 17, nameTr: 'İsrâ' },
  { number: 18, nameTr: 'Kehf' },
  { number: 19, nameTr: 'Meryem' },
  { number: 20, nameTr: 'Tâhâ' },
  { number: 21, nameTr: 'Enbiyâ' },
  { number: 22, nameTr: 'Hac' },
  { number: 23, nameTr: 'Mü’minûn' },
  { number: 24, nameTr: 'Nûr' },
  { number: 25, nameTr: 'Furkân' },
  { number: 26, nameTr: 'Şuarâ' },
  { number: 27, nameTr: 'Neml' },
  { number: 28, nameTr: 'Kasas' },
  { number: 29, nameTr: 'Ankebût' },
  { number: 30, nameTr: 'Rûm' },
  { number: 31, nameTr: 'Lokmân' },
  { number: 32, nameTr: 'Secde' },
  { number: 33, nameTr: 'Ahzâb' },
  { number: 34, nameTr: 'Sebe’' },
  { number: 35, nameTr: 'Fâtır' },
  { number: 36, nameTr: 'Yâsîn' },
  { number: 37, nameTr: 'Saffât' },
  { number: 38, nameTr: 'Sâd' },
  { number: 39, nameTr: 'Zümer' },
  { number: 40, nameTr: 'Mü’min (Gâfir)' },
  { number: 41, nameTr: 'Fussilet' },
  { number: 42, nameTr: 'Şûrâ' },
  { number: 43, nameTr: 'Zuhruf' },
  { number: 44, nameTr: 'Duhân' },
  { number: 45, nameTr: 'Câsiye' },
  { number: 46, nameTr: 'Ahkâf' },
  { number: 47, nameTr: 'Muhammed' },
  { number: 48, nameTr: 'Fetih' },
  { number: 49, nameTr: 'Hucurât' },
  { number: 50, nameTr: 'Kâf' },
  { number: 51, nameTr: 'Zâriyât' },
  { number: 52, nameTr: 'Tûr' },
  { number: 53, nameTr: 'Necm' },
  { number: 54, nameTr: 'Kamer' },
  { number: 55, nameTr: 'Rahmân' },
  { number: 56, nameTr: 'Vâkıa' },
  { number: 57, nameTr: 'Hadîd' },
  { number: 58, nameTr: 'Mücâdele' },
  { number: 59, nameTr: 'Haşr' },
  { number: 60, nameTr: 'Mümtehine' },
  { number: 61, nameTr: 'Saff' },
  { number: 62, nameTr: 'Cuma' },
  { number: 63, nameTr: 'Münafıkûn' },
  { number: 64, nameTr: 'Tegâbün' },
  { number: 65, nameTr: 'Talâk' },
  { number: 66, nameTr: 'Tahrîm' },
  { number: 67, nameTr: 'Mülk' },
  { number: 68, nameTr: 'Kalem' },
  { number: 69, nameTr: 'Hâkka' },
  { number: 70, nameTr: 'Me’âric' },
  { number: 71, nameTr: 'Nûh' },
  { number: 72, nameTr: 'Cin' },
  { number: 73, nameTr: 'Müzzemmil' },
  { number: 74, nameTr: 'Müddessir' },
  { number: 75, nameTr: 'Kıyâme' },
  { number: 76, nameTr: 'İnsan (Dehr)' },
  { number: 77, nameTr: 'Mürselât' },
  { number: 78, nameTr: 'Nebe’' },
  { number: 79, nameTr: 'Nâzi’ât' },
  { number: 80, nameTr: 'Abese' },
  { number: 81, nameTr: 'Tekvîr' },
  { number: 82, nameTr: 'İnfitâr' },
  { number: 83, nameTr: 'Mutaffifîn' },
  { number: 84, nameTr: 'İnşikâk' },
  { number: 85, nameTr: 'Bürûc' },
  { number: 86, nameTr: 'Târık' },
  { number: 87, nameTr: 'A’lâ' },
  { number: 88, nameTr: 'Gâşiye' },
  { number: 89, nameTr: 'Fecr' },
  { number: 90, nameTr: 'Beled' },
  { number: 91, nameTr: 'Şems' },
  { number: 92, nameTr: 'Leyl' },
  { number: 93, nameTr: 'Duha' },
  { number: 94, nameTr: 'İnşirâh (Şerh)' },
  { number: 95, nameTr: 'Tîn' },
  { number: 96, nameTr: 'Alak' },
  { number: 97, nameTr: 'Kadr' },
  { number: 98, nameTr: 'Beyyine' },
  { number: 99, nameTr: 'Zilzâl' },
  { number: 100, nameTr: 'Âdiyât' },
  { number: 101, nameTr: 'Kâria' },
  { number: 102, nameTr: 'Tekâsür' },
  { number: 103, nameTr: 'Asr' },
  { number: 104, nameTr: 'Hümeze' },
  { number: 105, nameTr: 'Fîl' },
  { number: 106, nameTr: 'Kureyş' },
  { number: 107, nameTr: 'Mâûn' },
  { number: 108, nameTr: 'Kevser' },
  { number: 109, nameTr: 'Kâfirûn' },
  { number: 110, nameTr: 'Nasr' },
  { number: 111, nameTr: 'Tebbet (Leheb)' },
  { number: 112, nameTr: 'İhlâs' },
  { number: 113, nameTr: 'Felak' },
  { number: 114, nameTr: 'Nâs' },
];

export const surahs: SurahMeta[] = NAMES.map(({ number, nameTr }) => ({
  number,
  nameTr,
  revelation: MEDENI_NUMBERS.has(number) ? 'Medeni' : 'Mekki',
}));
