export type RevelationType = "Mekki" | "Medeni";

export interface SurahMeta {
  number: number;
  nameTr: string;
  revelation: RevelationType;
  totalAyahs: number;
}

// Widely accepted Medenî (Medinan) surahs.
const MEDENI_NUMBERS = new Set<number>([
  2, 3, 4, 5, 8, 9, 13, 22, 24, 33, 47, 48, 49, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 76, 98, 99, 110,
]);

// Turkish surah names and verse counts (1-114)
const NAMES: Array<{ number: number; nameTr: string; totalAyahs: number }> = [
  { number: 1, nameTr: "Fâtiha", totalAyahs: 7 },
  { number: 2, nameTr: "Bakara", totalAyahs: 286 },
  { number: 3, nameTr: "Âl-i İmrân", totalAyahs: 200 },
  { number: 4, nameTr: "Nisâ", totalAyahs: 176 },
  { number: 5, nameTr: "Mâide", totalAyahs: 120 },
  { number: 6, nameTr: "En'âm", totalAyahs: 165 },
  { number: 7, nameTr: "A'râf", totalAyahs: 206 },
  { number: 8, nameTr: "Enfâl", totalAyahs: 75 },
  { number: 9, nameTr: "Tevbe", totalAyahs: 129 },
  { number: 10, nameTr: "Yûnus", totalAyahs: 109 },
  { number: 11, nameTr: "Hûd", totalAyahs: 123 },
  { number: 12, nameTr: "Yûsuf", totalAyahs: 111 },
  { number: 13, nameTr: "Ra'd", totalAyahs: 43 },
  { number: 14, nameTr: "İbrâhîm", totalAyahs: 52 },
  { number: 15, nameTr: "Hicr", totalAyahs: 99 },
  { number: 16, nameTr: "Nahl", totalAyahs: 128 },
  { number: 17, nameTr: "İsrâ", totalAyahs: 111 },
  { number: 18, nameTr: "Kehf", totalAyahs: 110 },
  { number: 19, nameTr: "Meryem", totalAyahs: 98 },
  { number: 20, nameTr: "Tâhâ", totalAyahs: 135 },
  { number: 21, nameTr: "Enbiyâ", totalAyahs: 112 },
  { number: 22, nameTr: "Hac", totalAyahs: 78 },
  { number: 23, nameTr: "Mü'minûn", totalAyahs: 118 },
  { number: 24, nameTr: "Nûr", totalAyahs: 64 },
  { number: 25, nameTr: "Furkân", totalAyahs: 77 },
  { number: 26, nameTr: "Şuarâ", totalAyahs: 227 },
  { number: 27, nameTr: "Neml", totalAyahs: 93 },
  { number: 28, nameTr: "Kasas", totalAyahs: 88 },
  { number: 29, nameTr: "Ankebût", totalAyahs: 69 },
  { number: 30, nameTr: "Rûm", totalAyahs: 60 },
  { number: 31, nameTr: "Lokmân", totalAyahs: 34 },
  { number: 32, nameTr: "Secde", totalAyahs: 30 },
  { number: 33, nameTr: "Ahzâb", totalAyahs: 73 },
  { number: 34, nameTr: "Sebe'", totalAyahs: 54 },
  { number: 35, nameTr: "Fâtır", totalAyahs: 45 },
  { number: 36, nameTr: "Yâsîn", totalAyahs: 83 },
  { number: 37, nameTr: "Saffât", totalAyahs: 182 },
  { number: 38, nameTr: "Sâd", totalAyahs: 88 },
  { number: 39, nameTr: "Zümer", totalAyahs: 75 },
  { number: 40, nameTr: "Mü'min (Gâfir)", totalAyahs: 85 },
  { number: 41, nameTr: "Fussilet", totalAyahs: 54 },
  { number: 42, nameTr: "Şûrâ", totalAyahs: 53 },
  { number: 43, nameTr: "Zuhruf", totalAyahs: 89 },
  { number: 44, nameTr: "Duhân", totalAyahs: 59 },
  { number: 45, nameTr: "Câsiye", totalAyahs: 37 },
  { number: 46, nameTr: "Ahkâf", totalAyahs: 35 },
  { number: 47, nameTr: "Muhammed", totalAyahs: 38 },
  { number: 48, nameTr: "Fetih", totalAyahs: 29 },
  { number: 49, nameTr: "Hucurât", totalAyahs: 18 },
  { number: 50, nameTr: "Kâf", totalAyahs: 45 },
  { number: 51, nameTr: "Zâriyât", totalAyahs: 60 },
  { number: 52, nameTr: "Tûr", totalAyahs: 49 },
  { number: 53, nameTr: "Necm", totalAyahs: 62 },
  { number: 54, nameTr: "Kamer", totalAyahs: 55 },
  { number: 55, nameTr: "Rahmân", totalAyahs: 78 },
  { number: 56, nameTr: "Vâkıa", totalAyahs: 96 },
  { number: 57, nameTr: "Hadîd", totalAyahs: 29 },
  { number: 58, nameTr: "Mücâdele", totalAyahs: 22 },
  { number: 59, nameTr: "Haşr", totalAyahs: 24 },
  { number: 60, nameTr: "Mümtehine", totalAyahs: 13 },
  { number: 61, nameTr: "Saff", totalAyahs: 14 },
  { number: 62, nameTr: "Cuma", totalAyahs: 11 },
  { number: 63, nameTr: "Münafıkûn", totalAyahs: 11 },
  { number: 64, nameTr: "Tegâbün", totalAyahs: 18 },
  { number: 65, nameTr: "Talâk", totalAyahs: 12 },
  { number: 66, nameTr: "Tahrîm", totalAyahs: 12 },
  { number: 67, nameTr: "Mülk", totalAyahs: 30 },
  { number: 68, nameTr: "Kalem", totalAyahs: 52 },
  { number: 69, nameTr: "Hâkka", totalAyahs: 52 },
  { number: 70, nameTr: "Me'âric", totalAyahs: 44 },
  { number: 71, nameTr: "Nûh", totalAyahs: 28 },
  { number: 72, nameTr: "Cin", totalAyahs: 28 },
  { number: 73, nameTr: "Müzzemmil", totalAyahs: 20 },
  { number: 74, nameTr: "Müddessir", totalAyahs: 56 },
  { number: 75, nameTr: "Kıyâme", totalAyahs: 40 },
  { number: 76, nameTr: "İnsan (Dehr)", totalAyahs: 31 },
  { number: 77, nameTr: "Mürselât", totalAyahs: 50 },
  { number: 78, nameTr: "Nebe'", totalAyahs: 40 },
  { number: 79, nameTr: "Nâzi'ât", totalAyahs: 46 },
  { number: 80, nameTr: "Abese", totalAyahs: 42 },
  { number: 81, nameTr: "Tekvîr", totalAyahs: 29 },
  { number: 82, nameTr: "İnfitâr", totalAyahs: 19 },
  { number: 83, nameTr: "Mutaffifîn", totalAyahs: 36 },
  { number: 84, nameTr: "İnşikâk", totalAyahs: 25 },
  { number: 85, nameTr: "Bürûc", totalAyahs: 22 },
  { number: 86, nameTr: "Târık", totalAyahs: 17 },
  { number: 87, nameTr: "A'lâ", totalAyahs: 19 },
  { number: 88, nameTr: "Gâşiye", totalAyahs: 26 },
  { number: 89, nameTr: "Fecr", totalAyahs: 30 },
  { number: 90, nameTr: "Beled", totalAyahs: 20 },
  { number: 91, nameTr: "Şems", totalAyahs: 15 },
  { number: 92, nameTr: "Leyl", totalAyahs: 21 },
  { number: 93, nameTr: "Duha", totalAyahs: 11 },
  { number: 94, nameTr: "İnşirâh (Şerh)", totalAyahs: 8 },
  { number: 95, nameTr: "Tîn", totalAyahs: 8 },
  { number: 96, nameTr: "Alak", totalAyahs: 19 },
  { number: 97, nameTr: "Kadr", totalAyahs: 5 },
  { number: 98, nameTr: "Beyyine", totalAyahs: 8 },
  { number: 99, nameTr: "Zilzâl", totalAyahs: 8 },
  { number: 100, nameTr: "Âdiyât", totalAyahs: 11 },
  { number: 101, nameTr: "Kâria", totalAyahs: 11 },
  { number: 102, nameTr: "Tekâsür", totalAyahs: 8 },
  { number: 103, nameTr: "Asr", totalAyahs: 3 },
  { number: 104, nameTr: "Hümeze", totalAyahs: 9 },
  { number: 105, nameTr: "Fîl", totalAyahs: 5 },
  { number: 106, nameTr: "Kureyş", totalAyahs: 4 },
  { number: 107, nameTr: "Mâûn", totalAyahs: 7 },
  { number: 108, nameTr: "Kevser", totalAyahs: 3 },
  { number: 109, nameTr: "Kâfirûn", totalAyahs: 6 },
  { number: 110, nameTr: "Nasr", totalAyahs: 3 },
  { number: 111, nameTr: "Tebbet (Leheb)", totalAyahs: 5 },
  { number: 112, nameTr: "İhlâs", totalAyahs: 4 },
  { number: 113, nameTr: "Felak", totalAyahs: 5 },
  { number: 114, nameTr: "Nâs", totalAyahs: 6 },
];

export const surahs: SurahMeta[] = NAMES.map(({ number, nameTr, totalAyahs }) => ({
  number,
  nameTr,
  totalAyahs,
  revelation: MEDENI_NUMBERS.has(number) ? "Medeni" : "Mekki",
}));
